ALTER TABLE TICKETS ADD DUE_DATE DATE;
ALTER TABLE TICKETS ADD ATTACHMENT_PATH VARCHAR2(500);

CREATE SEQUENCE BI_OJT.TICKETS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BI_OJT.TICKETS_NUM_SEQ START WITH 1 INCREMENT BY 1;