DECLARE
  start_val NUMBER;
BEGIN
  SELECT NVL(MAX(USER_ID),0) + 1 INTO start_val FROM USERS;

  BEGIN
    EXECUTE IMMEDIATE 
      'CREATE SEQUENCE USERS_SEQ START WITH ' || start_val || ' INCREMENT BY 1 NOCACHE NOCYCLE';
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE = -955 THEN
        NULL;
      ELSE
        RAISE;
      END IF;
  END;
END;
/
