//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BI_TICKETING_SYSTEM.Pages
{


    public partial class Tickets
    {

        protected global::System.Web.UI.WebControls.Panel pnlSuccess;

        protected global::System.Web.UI.WebControls.Label lblSuccess;

        protected global::System.Web.UI.WebControls.Panel pnlError;

        protected global::System.Web.UI.WebControls.Label lblError;

        protected global::System.Web.UI.WebControls.Panel pnlCreateBtn;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;

        protected global::System.Web.UI.WebControls.DropDownList ddlFilterPriority;

        protected global::System.Web.UI.WebControls.Repeater rptTickets;

        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        protected global::System.Web.UI.WebControls.Label lblPaginationInfo;

        protected global::System.Web.UI.WebControls.Button btnPrev;

        protected global::System.Web.UI.WebControls.Button btnNext;

        protected global::System.Web.UI.WebControls.Label lblNewTicketNumber;

        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;

        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescription;

        protected global::System.Web.UI.WebControls.TextBox txtCreatedBy;

        protected global::System.Web.UI.WebControls.TextBox txtCreatedDate;

        protected global::System.Web.UI.WebControls.Button btnCreateTicket;

        protected global::System.Web.UI.WebControls.Label lblViewTicketNumber;

        protected global::System.Web.UI.WebControls.Label lblViewStatus;

        protected global::System.Web.UI.WebControls.Label lblViewTitle;

        protected global::System.Web.UI.WebControls.Label lblViewDescription;

        protected global::System.Web.UI.WebControls.Label lblViewCreatedBy;

        protected global::System.Web.UI.WebControls.Label lblViewCreatedDate;

        protected global::System.Web.UI.WebControls.Label lblViewAssignedTo;

        protected global::System.Web.UI.WebControls.Label lblViewAssignedToRole;

        protected global::System.Web.UI.WebControls.Repeater rptRemarks;

        protected global::System.Web.UI.WebControls.Panel pnlNoRemarks;

        protected global::System.Web.UI.WebControls.HiddenField hfShowModal;

        protected global::System.Web.UI.WebControls.HiddenField hfSwalMessage;

        protected global::System.Web.UI.WebControls.HiddenField hfSwalType;
    }
}
